language: ruby
rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - ruby-head
before_install:
  - if [ ${TRAVIS_RUBY_VERSION} = '2.2' ]; then
      gem install bundler -v '< 2';
    else
      gem update --system;
      gem install bundler;
    fi
script:
  - bundle exec rubocop
  - bundle exec rspec
